-- 수집한 시간표를 담는 최초 스키마.
--
-- Hibernate 의 ddl-auto 가 만들어 준 모양을 그대로 옮기되, 제약 이름만 사람이 읽을 수 있게 바꿨다
-- (자동 생성된 `uk7taklq5tfdxh27cmom9268yu8` 같은 이름은 위반 로그가 떴을 때 무슨 제약인지 알 수 없다).
--
-- 이 파일은 한 번 배포되면 고치지 않는다. 스키마를 바꾸려면 V2, V3 을 새로 만든다.

CREATE TABLE store (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_key   VARCHAR(255) NOT NULL,
    brand       VARCHAR(255) NOT NULL,
    branch_name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_store_key UNIQUE (store_key)
);

CREATE TABLE theme (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        BIGINT       NOT NULL,
    -- 사이트가 준 테마 ID. 이름을 키로 잡으면 테마명이 바뀔 때 같은 테마가 두 행으로 갈라진다
    external_id     VARCHAR(255) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    genre           VARCHAR(255),
    capacity        VARCHAR(255),
    running_minutes INTEGER,
    horror_level    INTEGER,
    difficulty      INTEGER,
    poster_url      VARCHAR(500),
    CONSTRAINT fk_theme_store FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT uk_theme_store_external UNIQUE (store_id, external_id)
);

CREATE TABLE time_slot (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id        BIGINT      NOT NULL,
    slot_date       DATE        NOT NULL,
    slot_time       TIME(0)     NOT NULL,
    -- 이 값의 변화가 이 서비스의 전부다
    available       BOOLEAN     NOT NULL,
    last_checked_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_slot_theme FOREIGN KEY (theme_id) REFERENCES theme (id),
    CONSTRAINT uk_slot_theme_date_time UNIQUE (theme_id, slot_date, slot_time)
);

-- 조회 API 가 지점 하루치를 한 번에 읽는다 (`findByStoreAndDate`).
-- theme 를 거쳐 store 로 가므로 날짜 단독 인덱스가 실제로 쓰인다.
CREATE INDEX idx_slot_theme_date ON time_slot (theme_id, slot_date);
