-- 알림(M3) — 누가 어느 자리를 지켜보는지, 그리고 언제 알렸는지.

CREATE TABLE watch (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Firebase uid (토큰의 `sub`). 비밀번호는 우리 쪽을 지나가지 않는다
    user_id      VARCHAR(255) NOT NULL,
    time_slot_id BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_watch_slot FOREIGN KEY (time_slot_id) REFERENCES time_slot (id),
    -- 같은 자리를 두 번 신청할 수 없다. 버튼을 두 번 눌러도 알림은 한 번이다
    CONSTRAINT uk_watch_user_slot UNIQUE (user_id, time_slot_id)
);

-- 수집 한 바퀴에서 전이가 나면 "이 자리를 보던 사람" 을 슬롯 id 로 찾는다.
-- uk_watch_user_slot 은 user_id 가 앞이라 이 조회에 쓰이지 않는다.
CREATE INDEX idx_watch_slot ON watch (time_slot_id);

CREATE TABLE notification_log (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id BIGINT       NOT NULL,
    sent_at  TIMESTAMPTZ  NOT NULL,
    -- SENT | FAILED. 쿨다운은 SENT 만 센다 — 실패는 "알렸다" 가 아니다
    outcome  VARCHAR(255) NOT NULL,
    -- 감시를 지우면 그 기록도 같이 간다. 감시가 없으면 쿨다운도 의미가 없다
    CONSTRAINT fk_notification_watch FOREIGN KEY (watch_id) REFERENCES watch (id) ON DELETE CASCADE
);

-- 쿨다운 판정은 "이 감시의 마지막 SENT 가 언제냐" 하나뿐이다.
CREATE INDEX idx_notification_watch_sent ON notification_log (watch_id, sent_at DESC);
