-- 알림을 실제로 받을 기기. 감시(watch)는 "무엇을" 이고 이건 "어디로" 다.
--
-- 감시가 있어도 기기가 없으면 보낼 곳이 없다. 그 둘은 다른 사건이라 테이블도 나눈다 —
-- watch 에 토큰을 같이 넣으면 브라우저 하나에서 감시 열 개를 걸었을 때 같은 토큰이 열 벌 생기고,
-- 토큰이 만료됐을 때 열 군데를 고쳐야 한다.

CREATE TABLE device_token (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Firebase uid. watch.user_id 와 같은 값이다
    user_id    VARCHAR(255) NOT NULL,
    -- FCM 등록 토큰. 길이가 정해져 있지 않아 TEXT (지금은 160자쯤이지만 구글이 바꿔도 안 깨지게)
    token      TEXT         NOT NULL,
    -- 'web' | 'android' | 'ios'. 지금은 web 뿐이지만, 나중에 실패 원인을 나눠 보려면 필요하다
    platform   VARCHAR(32),
    updated_at TIMESTAMPTZ  NOT NULL,
    -- **user_id 가 아니라 token 이 유일하다.** 토큰은 "이 브라우저 설치" 를 가리키므로,
    -- 같은 기기에서 다른 계정으로 로그인하면 토큰의 주인이 바뀌어야 한다.
    -- (user_id, token) 으로 묶으면 이전 사용자 행이 남아 남의 폰으로 알림이 간다
    CONSTRAINT uk_device_token UNIQUE (token)
);

-- 발송은 항상 "이 사용자의 기기 전부" 로 시작한다
CREATE INDEX idx_device_token_user ON device_token (user_id);
